# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Minor Swing
tagline:          'Phoenix for Djangonauts'
description:      'My Phoenix learnings, where it differs from Django, where it excels and where it lags behind.'
url:              http://palm86.github.io

author:
  name:           'Daniel Palm'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/palm86/palm86.github.io
